services:
  mysql:
    image: "mysql:9.6"
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  valkey:
    image: "valkey/valkey:9.0-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "valkey-data:/data"

volumes:
  mysql-data:
  valkey-data:
